--liquibase formatted sql
--changeset author:mmordawski context:dev dbms:h2

DROP TABLE IF EXISTS `EMPLOYEE`;
CREATE TABLE `EMPLOYEE` (
  `ID` BIGINT NOT NULL,
  `EMPLOYEE_STATUS` VARCHAR(255),
  `FIRST_NAME` VARCHAR(100),
  `LAST_NAME` VARCHAR(100),
  `MOBILE` VARCHAR(255),
   `POSITION` VARCHAR(255) NOT NULL,
   PRIMARY KEY (ID)
);

DROP SEQUENCE IF EXISTS `HIBERNATE_SEQUENCE`;
CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 100003 INCREMENT BY 1;

INSERT INTO `EMPLOYEE` (ID,`EMPLOYEE_STATUS`, `FIRST_NAME`, `LAST_NAME`, `MOBILE`, `POSITION`) VALUES
(100000, 'EMPLOYEED', 'John', 'Doe', '123 456 789', 'ADMINISTRATOR'),
(100001, 'EMPLOYEED', 'Jack', 'Black', '987 654 321', 'COURIER'),
(100002, 'EMPLOYEED', 'Suzan', 'Wright', '789 456 123', 'SORTING');
