--liquibase formatted sql
--changeset author:mmordawski dbms:mysql

DROP TABLE IF EXISTS parcel;
CREATE TABLE parcel (ID int NOT NULL AUTO_INCREMENT, COURIER_ID VARCHAR(255), MODIFIED_BY VARCHAR(255), RECEIVER_CITY VARCHAR(255), RECEIVER_COUNTRY VARCHAR(255), RECEIVER_POSTAL_CODE VARCHAR(255), RECEIVER_STREET VARCHAR(255), RECEIVER_FIRST_NAME VARCHAR(255), RECEIVER_LAST_NAME VARCHAR(255), RECEIVER_PHONE VARCHAR(255), SENDER_CITY VARCHAR(255), SENDER_COUNTRY VARCHAR(255), SENDER_POSTAL_CODE VARCHAR(255), SENDER_STREET VARCHAR(255), SENDER_FIRST_NAME VARCHAR(255), SENDER_LAST_NAME VARCHAR(255), SENDER_PHONE VARCHAR(255), WEIGHT FLOAT, STATUS INTEGER NOT NULL, SEARCH_STRING VARCHAR(1000), PRIMARY KEY (ID)) AUTO_INCREMENT=1000000;
