--liquibase formatted sql
--changeset author:mmordawski context:prod dbms:h2

DROP TABLE IF EXISTS PARCEL;
CREATE TABLE PARCEL (ID BIGINT NOT NULL, COURIER_ID VARCHAR(255), MODIFIED_BY VARCHAR(255), RECEIVER_CITY VARCHAR(255), RECEIVER_COUNTRY VARCHAR(255), RECEIVER_POSTAL_CODE VARCHAR(255), RECEIVER_STREET VARCHAR(255), RECEIVER_FIRST_NAME VARCHAR(255), RECEIVER_LAST_NAME VARCHAR(255), RECEIVER_PHONE VARCHAR(255), SENDER_CITY VARCHAR(255), SENDER_COUNTRY VARCHAR(255), SENDER_POSTAL_CODE VARCHAR(255), SENDER_STREET VARCHAR(255), SENDER_FIRST_NAME VARCHAR(255), SENDER_LAST_NAME VARCHAR(255), SENDER_PHONE VARCHAR(255), WEIGHT FLOAT, STATUS INTEGER NOT NULL, SEARCH_STRING VARCHAR(1000), PRIMARY KEY (ID));

DROP SEQUENCE IF EXISTS `HIBERNATE_SEQUENCE`;
CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 1000000 INCREMENT BY 1;